In [1]:
import pandas as pd

pd.set_option('display.max_columns', 20)    # 设置显示列数
pd.set_option('display.max_rows', 30)       # 设置显示行数


#1.读取数据
df = pd.read_csv('素材/sales.csv')
print(df)


#2.数据清洗
#2.1 缺失值处理
# df.isnull() #查看缺失值

#2.1.1 删除缺失值
# df.dropna() #删除包含缺失值的行
# df  = df.dropna(axis=1) #删除包含缺失值的列
# df

#2.1.2 填充缺失值
# df.fillna('----') #用'----'填充缺失值
# df.ffill() #填充缺失值,填充上一行数据
# df.bfill() #填充缺失值,填充下一行数据

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [2]:
#2.2 重复值处理
#2.2.1 查看重复值
# df.duplicated() #查看所有重复值(所有的列的数据都重复)
# df.duplicated(subset=['订单号']) #查看订单号列是否有重复值(订单号列的数据重复)

# #2.2.2 删除重复值
# df.drop_duplicates() #删除所有重复值(所有的列的数据都重复)
# df.drop_duplicates(subset=['订单号']) #删除订单号列中的重复值(订单号列的数据重复) #keep = 'first' 保留第一个重复值 #keep = 'last' #保留最后一个重复值

In [3]:
#2.2.3 异常值处理
#2.2.3.1 查看异常值
df[df['单价']<0]

#2.2.3.2 删除异常值
#df.drop(df[df['单价']<0].index) #删除单价小于0的行

#2.2.3.3 修复异常值
df['单价'] = df['单价'].abs() #将单价列中的所有值取为绝对值
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]

In [4]:
#2.4数据格式处理
df['订单日期'] = df['订单日期'].str.replace(' /','-')
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3    6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
..          ...   ...   ...   ...  ...    ...   ...         ...
995  5887473055    图书    小说    10   49     长沙  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79     成都   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129     南京   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39     广州   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89     西安   银行卡  2026-03-20

[1000 rows x 8 columns]